if(EXISTS "/eos/user/s/svashish/FCCAnalyses_pre/addons/ONNXRuntime/onnxruntime-unittest_tests-b12d07c.cmake")
  include("/eos/user/s/svashish/FCCAnalyses_pre/addons/ONNXRuntime/onnxruntime-unittest_tests-b12d07c.cmake")
else()
  add_test(onnxruntime-unittest_NOT_BUILT-b12d07c onnxruntime-unittest_NOT_BUILT-b12d07c)
endif()
