if(EXISTS "/eos/user/s/svashish/FCCAnalyses_pre/tests/unittest/unittest_tests-b12d07c.cmake")
  include("/eos/user/s/svashish/FCCAnalyses_pre/tests/unittest/unittest_tests-b12d07c.cmake")
else()
  add_test(unittest_NOT_BUILT-b12d07c unittest_NOT_BUILT-b12d07c)
endif()
